apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: $(PVC_SIZE_GI)Gi