jobs:
  - script: >
      if ("${JOB_DSL_GIT_SOURCE}" == "github") {
      multibranchPipelineJob('seed-job-from-github') {
        displayName('seed-dsl-from-github')
        branchSources {
          github {
            id("${JOB_DSL_GITHUB_REPO}-seed-job") // IMPORTANT: use a constant and unique identifier
            scanCredentialsId("${JOB_DSL_GITHUB_REPO_CRED}")
            repoOwner("${JOB_DSL_GITHUB_REPO}".split("/")[0])
            repository("${JOB_DSL_GITHUB_REPO}".split("/")[1])
            apiUri("${GITHUB_API_URL}")
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(1)
          }
        }
        triggers {
          cron('*/5 * * * *') // Trigger every 5 minutes
          //hudsonStartupTrigger - Start job as soon as its build
          hudsonStartupTrigger {
            quietPeriod("0")
            runOnChoice("ON_CONNECT")
            label("${JENKINS_AGENT_LABEL}")
            nodeParameterName("")
          }
        }
        factory {
          inlineDefinitionBranchProjectFactory {
            // markerFile - should be available to decide if a repo should be consider job dsl repo.
            markerFile("${JOB_DSL_GIT_MARKER_FILE}")
            sandbox(true)
            script('''
              pipeline {
                  agent {
                    label "${JENKINS_AGENT_LABEL}"
                  }

                  triggers {
                      pollSCM('H * * * *')
                  }

                  options {
                    buildDiscarder(logRotator(numToKeepStr: '5'))
                    timeout(time: 30, unit: 'MINUTES')
                    timestamps()
                  }

                  stages {
                    stage("Process DSL") {
                      steps {
                        script {
                          def targets = sh(
                            // script: 'find . -type d -regextype posix-extended -not -regex "(.*/libs$|.*/libs/.*|.*/\\\\.git.*|./_stdlib)" -exec echo "{}/*.groovy" \\\\;',
                            // This script will use ${JOB_DSL_GITHUB_REPO_FOLDER} as the directory to scan, and if it's not defined or empty, it will fall back to the root folder /. This way, it will scan the root folder if ${JOBDSLFOLDER} is not specified.
                            script: 'find ${JOB_DSL_GITHUB_REPO_FOLDER:-/} -type f -name "*.groovy"',
                            returnStdout: true
                          )
                          println("--> target paths:\\n" + targets)

                          jobDsl(
                            ignoreMissingFiles:  true,
                            targets:             targets,
                            //additionalClasspath: "_stdlib",
                            removedJobAction:    'DELETE',
                            removedViewAction:   'DELETE'
                          )
                        }

                      }
                    }
                  }
                }
            '''.stripIndent())
          }
        }
      }
      }
