##################################
# kubernetes-credentials-provider
###################################

# The "Kubernetes Credentials Provider" is a Jenkins plugin designed to facilitate the management
# of Jenkins credentials by integrating with Kubernetes secrets. This plugin allows you to store 
# Jenkins credentials securely within Kubernetes secrets, ensuring a level of security and ease 
# of integration in a Kubernetes-based CI/CD environment