jenkins:
  clouds:
    - kubernetes:
          containerCap: ${K8S_MAX_AGENTS}
          defaultsProviderTemplate: "jnlp"
          directConnection: true
          name: "kubernetes"
          podLabels:
          - key: "Environment"
            value: "Nonprod"
          - key: "SecurityContext"
            value: "Internal"
          - key: "SecurityExposure"
            value: "Internal"
          - key: "velero.io/exclude-from-backup"
            value: "true"
          - key: "discard_events"
            value: "true"
          templates:
          - containers:
            - alwaysPullImage: true
              args: ""
              command: ""
              image: "${JENKINS_AGENT_JNLP_IMAGE}"
              name: "jnlp"
              resourceLimitCpu: "1"
              resourceLimitMemory: "1024Mi"
              resourceRequestCpu: "0.1"
              resourceRequestMemory: "512Mi"
              resourceRequestEphemeralStorage: "512Mi"
              ttyEnabled: true
              runAsUser: 1001
              workingDir: "/home/jenkins/agent"
            label: "jnlp"
            name: "jnlp"
            envVars:
            - envVar:
                key: "TZ"
                value: "Pacific/Auckland"
            # nodeSelector: "agentpool=privnodepool"
            serviceAccount: "${BUILD_POD_SERVICE_ACCOUNT}"
            nodeUsageMode: NORMAL
            podRetention: "never"
            yaml: |-
              apiVersion: v1
              kind: Pod
              spec:
                activeDeadlineSeconds: 86400
                tolerations:
                  - key: "RunPrivBuild"
                    value: "true"
                    effect: "NoSchedule"
            yamlMergeStrategy: "merge"
          - name: docker
            label: docker
            containers:
            - alwaysPullImage: true
              envVars:
              - envVar:
                  key: "DOCKER_TLS_CERTS_DIR"
                  value: "/certs"
              args: "99d"
              command: "sleep"
              image: "${JENKINS_AGENT_DOCKER_IMAGE}"
              name: "docker"
              resourceLimitCpu: "500m"
              resourceLimitMemory: "256Mi"
              resourceRequestCpu: "10m"
              resourceRequestMemory: "256Mi"
              workingDir: "/home/jenkins/agent"
            - alwaysPullImage: true
              # envVars:
              # - envVar:
              #     key: "DOCKER_TLS_CERTS_DIR"
              #     value: "/certs"
              # - envVar:
              #     key: "HTTPS_PROXY"
              #     value: "http://myproxy:10568"
              # - envVar:
              #     key: "NO_PROXY"
              #     value: ".nrsh13.hadoop.com,localhost"
              image: "${JENKINS_AGENT_DOCKER_IMAGE}"
              name: "dind"
              privileged: true
              resourceLimitCpu: "2"
              resourceLimitMemory: "2048Mi"
              resourceRequestCpu: "500m"
              resourceRequestMemory: "2048Mi"
              resourceRequestEphemeralStorage: "1024Mi"
              workingDir: "/home/jenkins/agent"
            yaml: |-
              spec:
                containers:
                - name: 'docker'
                  volumeMounts:
                  - mountPath: /certs
                    name: docker-certs
                  - mountPath: /var/run
                    name: docker-socket
                - name: 'dind'
                  volumeMounts:
                  - mountPath: /certs
                    name: docker-certs
                  - mountPath: /var/run
                    name: docker-socket
                  - mountPath: /var/lib/docker
                    name: docker
                volumes:
                - emptyDir: {}
                  name: docker-socket
                - emptyDir: {}
                  name: docker-certs
                - emptyDir: {}
                  name: docker
            yamlMergeStrategy: "merge"
          # dind only container generally used for explicit inheritance from downstream pod templates where communication with docker daemon happens from a build type image
          - name: dind
            label: dind
            containers:
            - alwaysPullImage: true
              # envVars:
              # - envVar:
              #     key: 'DOCKER_TLS_CERTS_DIR'
              #     value: '/certs'
              # - envVar:
              #     key: 'HTTPS_PROXY'
              #     value: 'http://myproxy.com:10568'
              # - envVar:
              #     key: 'NO_PROXY'
              #     value: '.nrsh13.hadoop.com,localhost'
              image: '${JENKINS_AGENT_DOCKER_IMAGE}'
              name: 'dind'
              privileged: true
              resourceLimitCpu: '2'
              resourceLimitMemory: '2048Mi'
              resourceRequestCpu: '500m'
              resourceRequestMemory: '2048Mi'
              resourceRequestEphemeralStorage: '1024Mi'
            yaml: |-
              spec:
                containers:
                - name: 'dind'
                  volumeMounts:
                  - mountPath: /certs
                    name: docker-certs
                  - mountPath: /var/run
                    name: docker-socket
                  - mountPath: /var/lib/docker
                    name: docker
                volumes:
                - emptyDir: {}
                  name: docker-socket
                - emptyDir: {}
                  name: docker-certs
                - emptyDir: {}
                  name: docker
            yamlMergeStrategy: 'merge'