jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "adadmin"
            description: "Global Jenkins Administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "Managed_Jenkins_Admins"
          - name: "users"
            description: "Jenkins Domain Users"
            permissions:
              - "Overall/Administer"  ## ADDED for NON AD admin User
              - "Job/Build"
              - "Job/Discover"
              - "Build Failure Analyzer/UpdateCauses"
              - "Job/Read"
              - "Job/ExtendedRead"
              - "Agent/Connect"
              - "Agent/ExtendedRead"
              - "Run/Replay"
              - "Run/Delete"
              - "Job/Cancel"
              - "Build Failure Analyzer/ViewCauses"
              - "Build Failure Analyzer/RemoveCause"
              - "Agent/Build"
              - "Job/Workspace"
              - "Credentials/View"
              - "Overall/SystemRead"
              - "Overall/Read"
            assignments:
              - ${USER_AD_GROUP}    