### Things to Change for New environment
# Remove init container from base/deploy.yaml, 
# In this file - Update namespaces, images, namespace.yaml under resources and All Literals.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins-dev

images:
- name: nrsh13/jenkins
  newName: nrsh13/jenkins
  newTag: latest #2-lts
  
commonLabels:
  app: jenkins

resources:
  - namespace.yaml
  - secrets/sealed-github-token.yaml
  - secrets/sealed-bitbucket-user-pass.yaml
  - secrets/sealed-bitbucket-ssh-key.yaml    

configMapGenerator:

- name: jenkins-casc
  behavior: merge
  files:
    - config/base_authorization.yaml
    - config/base_ad_bind.yaml

- name: jenkins-env
  behavior: merge
  literals:
    
    # Refer base/kustomization.yaml to see all available LITERALS/ENV Variables.

    ##### Jenkins.yaml Environment Variables #####
    - ADMIN_USER=admin
    - ADMIN_USER_PASSWORD=9992131312    
    - INGRESS_DOMAIN=nrsh13-hadoop.com
    - USER_AD_GROUP=A_MJ_NRSH13_Admins
    #- EXTRA_PLUGINS="Office-365-Connector matrix-auth:3.1.8 docker-plugin:1.3.0" # matrix-auth required when not using AD.

    ##### K8s Cloud Config Environment Variables  #####
    - JENKINS_AGENT_JNLP_IMAGE="nrsh13/inbound-agent:4.13"
    - JENKINS_AGENT_DOCKER_IMAGE="nrsh13/tool/docker:23-dind"

    ##### Seed Job Pipeline Repo Environment Variables ####
    - JOB_DSL_GIT_SOURCE=github
    - JOB_DSL_GIT_MARKER_FILE=README.md
    # Bitbucket
    - JOB_DSL_BITBUCKET_REPO=nrsh2929/managed-jenkins-jobs
    - JOB_DSL_BITBUCKET_REPO_BRANCH=master
    - JOB_DSL_BITBUCKET_REPO_CRED=bitbucket-user-pass
    # Github
    - GITHUB_API_URL=https://api.github.com
    - JOB_DSL_GITHUB_REPO_CRED=github-token
    - JOB_DSL_GITHUB_REPO=Nrsh13/k8s_and_ecs_deploy
    - JOB_DSL_GITHUB_REPO_FOLDER=managed_jenkins_jobs_dsl 

    ##### BITBUCKET ENDPOINT Configuration (not needed while using Github) #####
    - BITBUCKET_MANAGEMENT_CRED=bitbucket-user-pass
    - BITBUCKET_SERVER_URL=https://bitbucket.org
    - BITBUCKET_MANAGE_HOOKS=false	
    - GITHUB_APPROVED_HOST_KEY=github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
    - BITBUCKET_APPROVED_HOST_KEY=bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQeJzhupRu0u0cdegZIa8e86EG2qOCsIsD1Xw0xSeiPDlCr7kq97NLmMbpKTX6Esc30NuoqEEHCuc7yWtwp8dI76EEEB1VqY9QJq6vk+aySyboD5QF61I/1WeTwu+deCbgKMGbUijeXhtfbxSxm6JwGrXrhBdofTsbKRUsrN1WoNgUa8uqN1Vx6WAJw1JHPhglEGGHea6QICwJOAr/6mrui/oB7pkaWKHj3z7d1IC4KWLtY47elvjbaTlkN04Kc/5LFEirorGYVbt15kAUlqGM65pk6ZBxtaO3+30LVlORZkxOh+LKL/BvbZ/iRNhItLqNyieoQj/uh/7Iv4uyH/cV/0b4WDSd3DptigWq84lJubb9t/DnZlrJazxyDCulTmKdOR7vs9gMTo+uoIrPSb8ScTtvw65+odKAlBj59dhnVp9zd7QUojOpXlL62Aw56U4oO+FALuevvMjiWeavKhJqlR7i5n9srYcrNV7ttmDw7kf/97P5zauIhxcjX+xHv4M=

patches:
- path: request-ephemeral-storage-patch.yaml
- path: remove-pvc-patch.yaml
- path: change-volume-patch.yaml

resources:
- ../../base
