---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: github-token
spec:
  encryptedData:
    password: AgAaoqKPyptEIIjBpDUz+/NO4BRBCGd9EjEyjif6J8LfdD/Gniuh4Lsloa0U5KmEVO3DIOi0FLo/Wv64LFoqc3t2jWsZb3HN1tuxv4eBB3yrZ5JzleRt3A23KeR91w7lxHYMGq2CSkJ+mFA0xsVgdksuxzxi3mUxN+9x/6cSQOaWgjz+I86ZOTYjwP1So7FspmLElNpHMJf3jHHJ9PaMgwkRv8hFjJgbosxFm23nckn1hui6B3vRj6kW0I8GYXIsjB8RxamytL3yrFDgzP0MZo6LjMRnrM1OsbJ4KZxFHMmhguI8lBLECxBsLQ9MHAaehFPTquI2uMCtPcAb6hAOZNDIkk8ib+RoHkbQJtPngWlgOxYvN3gA9IgWJ0D7PqzGojywRRgzAxKC9fGpIpmBSb3hm2GokTDoVrasNjJSubx4ARgQ1WYbeVwMz1G2jRv6Ytw8aJ+6v96TmtlhpIuVHZ9zINllB/ciqWNeAX4HrX8e9Des6Vn6XJAC7/4/O+K6YkGgHgzOrsGbxHhwZc6wQDa9Ww5gLWVrg/ZSnGp6nShweCNBTFlUMsNxE5914sjpReV32cEpMW5l2N2dFygPG+6MuxAnd8hrhF+HMOTNgFq/xxzyBxKL0nOj3qA4TiIgHff17XQItF0dJEbAnB9cJYa5za7p24Dj661PcDT1Purlvuna65t2+GAFEzVZyCXiWHgg0KKtiIFy9l6ly50fnOKMVV1S/6NI9Gx+xRMJF/oFLk6hhQeaz7qHmOPhSfqnnNduYCAN4ZUEPHQToRTyJFcgIBDNOvC96TLthC2dBR/aEyjvpTs9bpeU08mquXA=
    username: AgAsp3sbKVqmsvzxVTrogGrw/eopclowu8eImW+rpiUiX2e28Nb5NZyJUBeZZzLgKnM9dZ77O5thxfOnn49ckTkEJnV95SrTlA5Rndfc0tInl1iNq6ZQt5K1g2+PLvEdIkKUuRTGGTT9zb9Q/+tKwnS4Vj49MMfyfHOT+7c/BN6u1Kg6FOBgKriETVMdlbaLKXsl/Zzcrqw3mIdfc1RW0OkJQD742cBnKvAbGao27rE7Rpk15xiJMvwzGl4/Lzq6YjOUaTCO6rBJG1jq8sWmtRMBv2zeQHeYDVxpqgOSrAoFFmo6x0a8IYFz/4onwB9Sm4bjQmaRMU6iqnK45yr+n3014t7caKcqTtxFyN66w4CUKc5UlELeHFHwW/Qe3fTKn309LCoIX2XtXPgtRKczbc0FV/v3Jcmi0rxN7YQ3i4gfi28fnU8dgxLBQCzLVVO99e6U5erQsBRYTp75LWSua+8aIxNft4/vAfpBXDGlJl6nOaeBPhqD9FDhjGp/OWgrNCHjZib7Nv/EcvOMT4tfqa8YwoVdDTj1W+p9MdMvj7sgoemanI6YYH8tA1ipgN1xaOERfLp6tblPhIyVyqYIbTm/tfZPSlIdDlP4ac4CZvrMR7M8r2eGAzt/9/CLCNldUwj5gVYJoAZcUieK1HyvYT9BQLmb/X33Peuvsw/Ft7YjUepfBdIc5p9O1LdRMHhWRtdSFiFewiU=
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: Github Credentials from K8s Secrets
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        jenkins.io/credentials-type: usernamePassword
      name: github-token
    type: Opaque
