---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: bitbucket-user-pass
spec:
  encryptedData:
    password: AgAYS5aMWPQpxwKyJ8EIj7FNQ7BqC+M7K5FBRltZCVfZmI+Ur92jPQgqbwuU51d4umXbKE4QFcWJpebH0kFMK542vzD3WJyhABcNsvl8YQkcuB+nfSQDKn3bls51QYdOo/8yNWX14lAF+r9y2bz3LZ05jccz02JaSVXHPGTmITtJL9yOKNMpifD5W2lt3c4xKi6jwNzAvFx3Z5LOI/CJwcn/NnBCfJEjQoNCHwotDhCc8xOVZrIUeriEdIdQN+mmYB5hDVMWFmOoXlvI+cvO5njr+xIbn94Eau0lI1r1GSf2IUbhmmbQVAcgbtmrjaKul/J1WYSD2pWf+fI5Hpyhd6IIWoMrO5mYkj4ycVN02sHaTW0mqMAeRAxc+Rh5+yKdV2uK4ue2rgnrWMAwpg8sIt3LB52rNNofH1987BTg6j811wEYlOl4VktLvCo9Bc1kctA7UYjIEk0ynQOsa3q6rul679nNhvU3WhHVZg9YXBLTgGmeotxE77jDKt5rBM9PFNdwL9s4ZLeJCCGwk+kTP1dmp31PUtiFBGNo2d0mr58Nql5uZQcpxreZlxVDUtQ3vc0AoYyDOCN5NkubTWpIH8XwV3/Zawfb6yAKQrdTxXo6xRS5+DFf59JxnarJz5FhDicQNrs+t6vI1XS4rH0bmxK2IUDAnXiiQyrilPjRubrB8i9CmhPKrnmOPgap7JFdW5L8/9fesdV2DbVWaSsaKoyoa1ZJFLOZX2Z11ItxD/W6I/sLlBI=
    username: AgBtsPqG0EFp8BTEJlQg1KKfCvutqtR8oVUETssnvPjqRNxzNs1bq9w8bAjDZg+aWNHjl/5r1wDTDRl3YsY+6D7mTZdMItmmFhYm6iAk3bO7j6NiJBZzf8iA/ho3tgmKgR2h1+he2lLafehRGUm0+xUxpaDOMEXrkSeA74lsHgiM3GHJNwI40rSLTjXTH8IOAnPofaw+THoSCcQpLxwbRC3CgbT2wQFFVNiEU4ppErUbB50hpLe8EyYIAouksORUV8KKGCgtW3CUvt64ETaey8u/033lJjKnG2R1EabCZAnWr1/rlFVptmiDU2b/9DAkxBaGNST6Br96azvt1hY0AKvBxJNifCNtWedlxmuXEI8Ja7CVicI18Lg5M4pax3+j0JQ7Mh97svBHoyDPYjzb5xV0m5gWg6444u8cB1T4NgOQYCiRcqBBu2h67WimEfM8PX84sm23SCzrviF8gy0IQdud0XwuqFJV8riPtthFL8+gqRk3njR9DjFBGRVwfQRKkBAJEiGhV9YwQtzjSZe78UJC25Glz66gXmbXbWGXAa5VGJ+2HWoLgtGJRZeAzvRpFym/WjG9FfU8i5Wir7JBo3HXWshop+bIXueX28+AK/JC9PpSd9qq5SG9xEL8NqNnzrECeap60dr4JPi6FQpNLioSEFu8JzznhvTgPnMUjvR5Z0P/EQ0KaobKq6dnn/BU7zLF+SZnZXk=
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: Bitbucket Credentials from K8s Secrets
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        jenkins.io/credentials-type: usernamePassword
      name: bitbucket-user-pass
    type: Opaque
