jenkins:
  securityRealm:
    activeDirectory:
      cache:
        size: 256
        ttl: 3600
      customDomain: true
      domains:
      - bindName: "NRSH13"
        bindPassword: "${readFile:/secret/jenkins-ad-bind.txt}"
        name: "NRSH13.HADOOP.COM"
        servers: "LDAPServer-01.com:3268,LDAPServer-02.com:3268"
        tlsConfiguration: JDK_TRUSTSTORE
      groupLookupStrategy: RECURSIVE
      removeIrrelevantGroups: false
      startTls: true
